export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const listingConstants = {
  GET_ALL_LISTINGS_REQUEST: "GET_ALL_LISTINGS_REQUEST",
  GET_ALL_LISTINGS_SUCCESS: "GET_ALL_LISTINGS_SUCCESS",
  GET_ALL_LISTINGS_FAILURE: "GET_ALL_LISTINGS_FAILURE",

  CREATELISTING_REQUEST: "CREATELISTING_REQUEST",
  CREATELISTING_SUCCESS: "CREATELISTING_SUCCESS",
  CREATELISTING_FAILURE: "CREATELISTING_FAILURE",

  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",

  DELETE_LISTING_REQUEST: "DELETE_LISTING_REQUEST",
  DELETE_LISTING_SUCCESS: "DELETE_LISTING_SUCCESS",
  DELETE_LISTING_FAILURE: "DELETE_LISTING_FAILURE",
};